version: '3.8'

services:
  rsvp-api:
    build:
      context: ./
      dockerfile: ./rsvp-api/Dockerfile
    container_name: rsvp-api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - rsvp-network
    depends_on:
      - rsvp-db
      - rsvp-tg

  rsvp-tg:
    build:
      context: ./
      dockerfile: ./rsvp-tg/Dockerfile
    container_name: rsvp-tg
    restart: unless-stopped
    env_file: .env
    networks:
      - rsvp-network

  rsvp-db:
    image: 'postgres' # use latest official postgres version
    env_file: .env
    volumes:
      - rsvp-db:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - rsvp-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - rsvp-network
    depends_on:
      - rsvp-api
volumes:
  rsvp-db:
networks:
  rsvp-network:
    driver: bridge
